name: get_daily_data_Bolivia_3
    
on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 14 * * *" # UTC time
  pull_request:
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner.
        - name: setup python
          uses: actions/setup-python@v2
          with:
                python-version: '3.9' #install the python needed
        - name: setup python
          run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
        - name: execute py script # run the script to get the latest data
          run: |
            python ./Step_1-Parse/code/data_read_processing.py
          env:
            key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
        - name: commit files
          run: |
            git config --local user.email "actions@users.noreply.github.com"
            git config --local user.name "Automated"
            git add -A
            timestamp=$(date -u)
            git commit -m "update data on: ${timestamp}" -a --allow-empty

        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main  
